### ISSUE TITLE
It should be possible to close pre-opened file descriptors

### ISSUE THREAD

**Issue by sunfishcode** [WebAssembly/wasi-classic-command#2]
Pre-opened file descriptors allow applications to accept capabilities at startup time. However, it would be useful to allow applications to decide that they no longer need certain capabilities, and close them, effectively dropping privileges.

**Comment by sunfishcode** [comment]
Right now, `wasi_unstable` follows the POSIX semantics of not closing derived file descriptors when a parent is closed. It would be awkward to require programs to hold directories open after they've opened the files they want.

Hosts rescinding access to resources that applications have open is called revocation, and there are ways to do it in the literature, which will be easier for us to discuss once wasm has more language features, so I propose it's not a priority for us to focus on right now.

**Comment by KronicDeth** [comment]
Closing derived file descriptors would clash with the standard practice of software shedding permissions as soon as they have a smaller subset they actually need to keep open, so that if they are exploited they have least privilege even if they started as running as root with access to the whole disk.  This is how most web servers work even outside of any child processes they may fork.

**Comment by sunfishcode** [comment]
In preview2, preopens are just regular handles, which can be dropped (closed).
