### ISSUE TITLE
Make environ_get require a capability

### ISSUE THREAD

**Issue by tschneidereit** [WebAssembly/wasi-classic-command#4]
Same as for [`random_get`](https://github.com/WebAssembly/WASI/issues/185), `environ_get` probably also should require a capability, as pointed out by @erights in an [issue in the Wasmtime repo](https://github.com/bytecodealliance/wasmtime/issues/748).

**Comment by erights** [comment]
Just noting that it was originally pointed out to me by @dckc . In any case, I agree. Thanks @tschneidereit .

The next message in that thread, by @sunfishcode links to https://github.com/WebAssembly/wasi-clocks/issues/4 . I notice that https://github.com/bytecodealliance/wasmtime/issues/748 is closed and https://github.com/WebAssembly/wasi-clocks/issues/4 is open. What are the status of those really? How does this issue relate to those?

**Comment by erights** [comment]
And what is the plural of "status" anyway?

**Comment by sunfishcode** [comment]
The status of bytecodealliance/wasmtime#748 is that this is a WASI spec issue, rather than a Wasmtime-specific issue, so we're tracking it in the WASI issue tracker. Wasmtime will follow the spec as it evolves.

The big-picture status on these from a WASI perspective is that we've been waiting for more of the underlying infrastructure to develop before making these changes, and it's at the point where we can now start designing Typed Main, a mechanism for passing capabilities into programs, and I'm going to be giving a presentation on it at this Thursday's WASI Subgroup meeting.

**Comment by sunfishcode** [comment]
And, I should add, we can use Typed Main to pass handles for clocks, random sources, and other capability handles in, which will be how I envision we'll address this issue.

**Comment by sunfishcode** [comment]
As with https://github.com/WebAssembly/wasi-classic-command/issues/5, the plan is now to make environment variables be arguments to the entrypoint. https://github.com/WebAssembly/WASI/issues/509 is now the place to follow this.
